### ISSUE TITLE
[feature] 프로젝트 상세 페이지 개발

### ISSUE THREAD

**Issue by gn00py48** [Line4thon-PROG/prog-frontend#5]
## ✔️ Issue

- 프로젝트 상세 페이지 개발 

## 📝 To-do

- [ ] 요약 보기 컴포넌트 작성
- [ ] 프로젝트 설명 컴포넌트 작성
- [ ] 고민 부분 컴포넌트 작성
- [ ] 백엔드 연

## 🛠 Working time

- 5 day
